name: flutter_chat_core
version: 3.10.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  cross_file: ^0.3.4+1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  mime: ^1.0.5
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
